language: python
dist: focal
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "pypy2"
    - "pypy3"
install:
    - pip install coveralls coverage
    - pip install -U setuptools
    - pip install zc.buildout
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
