language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3.3-5.2-alpha1"
include:
    matrix:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install coveralls coverage
    - pip install -U setuptools
    - pip install zc.buildout
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
